INSERT INTO `BulkType` (`displayName`, `type`)
VALUES
('Aluminium', 'ALUMINIUM'),
('Construction Sand', 'CONSTRUCTION_SAND'),
('Quartz Sand', 'QUARTZ_SAND'),
('Asphalt', 'ASPHALT'),
('Bauxite', 'BAUXITE'),
('Sulphur', 'SULPHUR'),
('Iron Ore', 'IRON_ORE'),
('Nickel Ore', 'NICKEL_ORE'),
('Cement', 'CEMENT'),
('Gypsum', 'GYPSUM'),
('Granite', 'GRANITE'),
('Boulder Stone', 'BOULDER_STONE'),
('Gravel', 'GRAVEL'),
('Split Stone', 'SPLIT_STONE'),
('Limestone', 'LIMESTONE'),
('Manganese', 'MANGANESE'),
('Copper', 'COPPER'),
('Bronze', 'BRONZE'),
('Tin', 'TIN'),
('Clay', 'CLAY'),
('Timber', 'TIMBER'),
('Construction Equipment', 'CONSTRUCTION_EQUIPMENT'),
('Gold Ore', 'GOLD_ORE'),
('Silver Ore', 'SILVER_ORE'),
('Granite (Boulder)', 'GRANITE_BOULDER'),
('Palm Kernel Shell', 'PALM_KERNEL_SHELL'),
('Fertilizer', 'FERTILIZER'),
('Container', 'CONTAINER'),
('Heavy Machinery', 'HEAVY_MACHINERY'),
('Trucks', 'TRUCKS'),
('Cranes', 'CRANES'),
('Foundation Pile', 'FOUNDATION_PILE'),
('Precast Construction', 'PRECAST_CONSTRUCTION');

INSERT INTO `ShipType` (`displayName`, `type`)
VALUES
('TB', 'Tug Boat'),
('BG', 'Barge'),
('LCT', 'LCT'),
('SPOB', 'Self Propelled Oil Barge'),
('SPB', 'Self Propelled Barge'),
('TANKER', 'Tanker'),
('CS', 'Container Ship'),
('MV', 'Bulk Carrier Mother Vessel'),
('DCS', 'Dry Cargo Ship'),
('RORO', 'Roll On Roll Off Ferry');

INSERT INTO `Incoterms` (`displayName`, `type`)
VALUES
('FOB', 'Free On Board'),
('CFR', 'Cost And Freight'),
('CIF', 'Cost, Insurance and Freight'),
('FAS', 'Free Alongside Ship'),
('EXW', 'Ex Works'),
('FCA', 'Free Carrier'),
('CPT', 'Carriage Paid To'),
('CIP', 'Carriage And Insurance Paid To'),
('DAT', 'Delivered At Terminal'),
('DAP', 'Delivered At Place'),
('DDP', 'Delivered Duty Paid');
