INSERT INTO `BulkType` (`displayName`, `type`)
VALUES
('Aluminium', 'ALUMINIUM'),
('Construction Sand', 'CONSTRUCTION_SAND'),
('Quartz Sand', 'QUARTZ_SAND'),
('Asphalt', 'ASPHALT'),
('Bauxite', 'BAUXITE'),
('Sulphur', 'SULPHUR'),
('Iron Ore', 'IRON_ORE'),
('Nickel Ore', 'NICKEL_ORE'),
('Cement', 'CEMENT'),
('Gypsum', 'GYPSUM'),
('Granite', 'GRANITE'),
('Boulder Stone', 'BOULDER_STONE'),
('Gravel', 'GRAVEL'),
('Split Stone', 'SPLIT_STONE'),
('Limestone', 'LIMESTONE'),
('Manganese', 'MANGANESE'),
('Copper', 'COPPER'),
('Bronze', 'BRONZE'),
('Tin', 'TIN'),
('Clay', 'CLAY'),
('Timber', 'TIMBER'),
('Construction Equipment', 'CONSTRUCTION_EQUIPMENT'),
('Gold Ore', 'GOLD_ORE'),
('Silver Ore', 'SILVER_ORE'),
('Granite (Boulder)', 'GRANITE_BOULDER'),
('Palm Kernel Shell', 'PALM_KERNEL_SHELL'),
('Fertilizer', 'FERTILIZER'),
('Container', 'CONTAINER'),
('Heavy Machinery', 'HEAVY_MACHINERY'),
('Trucks', 'TRUCKS'),
('Cranes', 'CRANES'),
('Foundation Pile', 'FOUNDATION_PILE'),
('Precast Construction', 'PRECAST_CONSTRUCTION');
